export const DOMAIN_ACTIONS = {
  MOVE: 'MOVE',
  OPEN_TAB: 'OPEN_TAB',
  SELECT_ITEM: 'SELECT_ITEM',
  CONFIRM: 'CONFIRM',
  BACK: 'BACK',
  TICK: 'TICK'
};

export const INPUT_ACTIONS = {
  UP: 'UP',
  DOWN: 'DOWN',
  LEFT: 'LEFT',
  RIGHT: 'RIGHT',
  A: 'A',
  B: 'B',
  TAB_MAP: 'TAB_MAP',
  TAB_BAG: 'TAB_BAG',
  TAB_MON: 'TAB_MON',
  MOVE_UP: 'MOVE_UP',
  MOVE_DOWN: 'MOVE_DOWN',
  MOVE_LEFT: 'MOVE_LEFT',
  MOVE_RIGHT: 'MOVE_RIGHT'
};

export const DIRECTIONS = {
  UP: 'up',
  DOWN: 'down',
  LEFT: 'left',
  RIGHT: 'right'
};

export const MENU_TABS = {
  MAP: 'MAP',
  BAG: 'BAG',
  MON: 'MON'
};

export const INPUT_TABS = {
  [INPUT_ACTIONS.TAB_MAP]: MENU_TABS.MAP,
  [INPUT_ACTIONS.TAB_BAG]: MENU_TABS.BAG,
  [INPUT_ACTIONS.TAB_MON]: MENU_TABS.MON
};

export const INPUT_TO_MOVE = {
  [INPUT_ACTIONS.MOVE_UP]: DIRECTIONS.UP,
  [INPUT_ACTIONS.MOVE_DOWN]: DIRECTIONS.DOWN,
  [INPUT_ACTIONS.MOVE_LEFT]: DIRECTIONS.LEFT,
  [INPUT_ACTIONS.MOVE_RIGHT]: DIRECTIONS.RIGHT
};
